version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: dosuzer/crm_backend:latest
    restart: always
    volumes:
      - static_backend_value:/app/static_backend/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: bjorn1986/crm_frontend:latest
    volumes:
      - result_build:/app/result_build/
    depends_on:
      - backend
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_backend_value:/var/html/static_backend/
      - media_value:/var/html/media/
      - result_build:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  postgres_data:
  result_build:
  static_backend_value:
  media_value:
