# Generated by Django 4.1 on 2023-07-26 04:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='Должность')),
                ('salary', models.CharField(max_length=50, verbose_name='Желаемая зарплата')),
                ('working_trip', models.BooleanField(blank=True, null=True, verbose_name='Командировка')),
                ('phone_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('relocation', models.CharField(choices=[('VZ', 'Возможен'), ('NV', 'Невозможен'), ('GL', 'Желателен'), ('NG', 'Нежелателен')], max_length=2, verbose_name='Переезд')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('W', 'Женский')], max_length=1, verbose_name='Пол')),
                ('marital_status', models.CharField(choices=[('N', 'Холост(Не замужем)'), ('Y', 'Женат(Замужем)')], max_length=1, verbose_name='Семейное положение')),
                ('education', models.CharField(choices=[('SN', 'Среднее неполное'), ('SR', 'Среднее'), ('SP', 'Среднее профессиональное'), ('VN', 'Высшее неполное'), ('VS', 'Высшее')], max_length=2, verbose_name='Образование')),
                ('town', models.CharField(max_length=50, verbose_name='Город проживания')),
                ('citizenship', models.CharField(max_length=50, verbose_name='Гражданство')),
                ('bday', models.DateField(verbose_name='Дата рождения')),
                ('about_me', models.TextField(max_length=700, verbose_name='Коротко о себе')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_resumes', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
            ],
            options={
                'verbose_name': 'Резюме',
                'ordering': ['job_title'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_title', models.CharField(max_length=100, verbose_name='Название компании')),
                ('about_company', models.TextField(help_text='Введите информацию о компани', verbose_name='О компании')),
                ('company_address', models.CharField(max_length=100, verbose_name='Адрес компании')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл.почта')),
                ('phoneNumber', models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('link_hr', models.URLField(max_length=100, null=True, verbose_name='Ссылка на HR')),
            ],
            options={
                'verbose_name': 'Основная информация о компании',
                'ordering': ['company_title'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата устроения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('organization', models.CharField(max_length=50, verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Опыт работы',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_title', models.CharField(max_length=100, verbose_name='Название вакансии')),
                ('required_experience', models.CharField(choices=[('1', 'Нет опыта'), ('2', '1-3 года'), ('3', '3-6 лет'), ('4', 'Более 6 лет')], max_length=1, verbose_name='Требуемый опыт работы')),
                ('about_company', models.TextField(help_text='Введите информацию о компани', verbose_name='О компании')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации вакансии')),
                ('job_conditions', models.TextField(help_text='Введите условия работы', verbose_name='Условия работы')),
                ('job_responsibilities', models.TextField(help_text='Введите обязанности кондидата', verbose_name='Обязанности кондидата')),
                ('technology_stack', models.TextField(verbose_name='Ключевые навыки')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancys', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancys', to='recruitment.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Основная информация о вакансии',
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_institution', models.CharField(max_length=250, verbose_name='Учебное заведение')),
                ('faculty', models.CharField(max_length=100, verbose_name='Факультет')),
                ('specialization', models.CharField(max_length=100, verbose_name='Специальность')),
                ('graduation', models.DateField(blank=True, null=True, verbose_name='Год окончания')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='recruitment.applicantresume', verbose_name='резюме')),
            ],
            options={
                'verbose_name': 'Информация об образовавании',
                'ordering': ['graduation'],
            },
        ),
        migrations.AddField(
            model_name='applicantresume',
            name='work_experiences',
            field=models.ManyToManyField(to='recruitment.workexperience', verbose_name='Информация об опыте работы'),
        ),
    ]
