# Generated by Django 4.1 on 2023-07-26 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantresume',
            name='employment_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PO', 'Полная'), ('CH', 'Частичная'), ('PR', 'Проектная'), ('ST', 'Стажировка'), ('VO', 'Волонтерство')], default='PO', max_length=14, verbose_name='Тип занятости'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantresume',
            name='schedule_work',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('P', 'Полный день'), ('S', 'Сменный график'), ('G', 'Гибкий график'), ('U', 'Удаленная работа'), ('W', 'Вахтовый метод')], default='1', max_length=9, verbose_name='Расписание работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PO', 'Полная'), ('CH', 'Частичная'), ('PR', 'Проектная'), ('ST', 'Стажировка'), ('VO', 'Волонтерство')], default=['PO'], max_length=14, verbose_name='Тип занятости'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='schedule_work',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('P', 'Полный день'), ('S', 'Сменный график'), ('G', 'Гибкий график'), ('U', 'Удаленная работа'), ('W', 'Вахтовый метод')], default=['P'], max_length=9, verbose_name='Расписание работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='recruitment.company', verbose_name='Компания'),
        ),
    ]
