# Generated by Django 4.1 on 2023-07-29 14:35

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_applicantresume_employment_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantresume',
            options={'ordering': ['job_title'], 'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company_title'], 'verbose_name': 'Основная информация о компании', 'verbose_name_plural': 'Основная информация о компании'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['graduation'], 'verbose_name': 'Информация об образовавании', 'verbose_name_plural': 'Информация об образовавании'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['pub_date'], 'verbose_name': 'Основная информация о вакансии', 'verbose_name_plural': 'Основная информация о вакансии'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name': 'Опыт работы', 'verbose_name_plural': 'Опыт работы'},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='applicantresume',
            name='employment_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PO', 'Полная'), ('CH', 'Частичная'), ('PR', 'Проектная'), ('ST', 'Стажировка'), ('VO', 'Волонтерство')], default=['PO'], max_length=14, verbose_name='Тип занятости'),
        ),
        migrations.AlterField(
            model_name='applicantresume',
            name='schedule_work',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('P', 'Полный день'), ('S', 'Сменный график'), ('G', 'Гибкий график'), ('U', 'Удаленная работа'), ('W', 'Вахтовый метод')], default=['P'], max_length=9, verbose_name='Расписание работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job_responsibilities',
            field=models.TextField(help_text='Введите обязанности кандидата', verbose_name='Обязанности кандидата'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала работы'),
        ),
    ]
