# Generated by Django 4.1 on 2023-08-29 15:17

import django.core.validators
from django.db import migrations, models
import recruitment.utils


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresume',
            name='citizenship',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='applicantresume',
            name='education',
            field=models.CharField(blank=True, choices=[('SR', 'Среднее'), ('VN', 'Высшее неполное'), ('VS', 'Высшее'), ('RC', 'Переподготовка')], max_length=2, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='applicantresume',
            name='town',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='interview_status',
            field=models.CharField(choices=[('PS', 'Первичный скрининг'), ('IHR', 'Интервью с HR'), ('IHD', 'Интервью с руководителем'), ('TT', 'Тестовое задание'), ('CTT', 'Выполнил тестовое задание'), ('IT', 'Интервью с командой'), ('OFFER', 'Оффер'), ('OC', 'Оффер принят')], default='PS', max_length=5, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(default='89501002030', max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=recruitment.utils.upload_to_candidates, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.CharField(max_length=40, verbose_name='Город'),
        ),
    ]
