# Generated by Django 4.1 on 2023-08-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_applicantresume_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company_title'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['pub_date'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
