# Generated by Django 4.1 on 2023-08-09 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_applicantresume_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantresume',
            name='current_company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Текущее место работы'),
        ),
        migrations.AddField(
            model_name='applicantresume',
            name='current_job',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Текущяя должность'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес офиса'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Город офиса'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Срок закрытия вакансии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Оплата труда'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('A', 'Активные'), ('F', 'Завернешшые'), ('D', 'Черновики')], default='D', max_length=1, verbose_name='Статус вакансии'),
        ),
    ]
