# Generated by Django 4.1 on 2023-08-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_applicantresume_current_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(verbose_name='Срок закрытия вакансии'),
        ),
    ]
