# Generated by Django 4.1 on 2023-09-09 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_alter_vacancy_deadline_alter_workexperience_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='custom_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Собственный статус'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='interview_status',
            field=models.CharField(blank=True, choices=[('PS', 'Первичный скрининг'), ('IHR', 'Интервью с HR'), ('IHD', 'Интервью с руководителем'), ('TT', 'Тестовое задание'), ('CTT', 'Выполнил тестовое задание'), ('IT', 'Интервью с командой'), ('OFFER', 'Оффер'), ('OC', 'Оффер принят')], max_length=5, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(default=datetime.date(2023, 10, 9), verbose_name='Срок закрытия вакансии'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 9, 9), null=True, verbose_name='Дата увольнения'),
        ),
    ]
