# Generated by Django 4.1 on 2023-08-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_alter_vacancy_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='about_company',
            field=models.TextField(blank=True, help_text='Введите информацию о компани', null=True, verbose_name='О компании'),
        ),
    ]
