# Generated by Django 4.1 on 2023-09-10 16:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_candidate_custom_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_status',
            field=models.CharField(choices=[('A', 'activeCandidates'), ('F', 'favoritesCandidates'), ('R', 'rejectedCandidates'), ('T', 'trialCandidates'), ('S', 'standbyCandidates')], default='A', max_length=1, verbose_name='Статус кандидата'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='interview_status',
            field=models.CharField(blank=True, choices=[('PS', 'Первичный скрининг'), ('IHR', 'Интервью с HR'), ('IHD', 'Интервью с руководителем'), ('TT', 'Тестовое задание'), ('CTT', 'Выполнил тестовое задание'), ('IT', 'Интервью с командой'), ('OFFER', 'Оффер'), ('OC', 'Оффер принят')], max_length=5, null=True, verbose_name='Статус прохождения'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recruitment.note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='recruitment.candidate'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(default=datetime.date(2023, 10, 10), verbose_name='Срок закрытия вакансии'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 9, 10), null=True, verbose_name='Дата увольнения'),
        ),
    ]
