# Generated by Django 4.1 on 2023-09-20 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_alter_comment_options_alter_note_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Список навыков',
                'verbose_name_plural': 'Списки навыков',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='technology_stack',
        ),
        migrations.AlterField(
            model_name='applicantresume',
            name='current_job',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Текущая должность'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(default=datetime.date(2023, 10, 20), verbose_name='Срок закрытия вакансии'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 9, 20), null=True, verbose_name='Дата увольнения'),
        ),
        migrations.CreateModel(
            name='SkillStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_stack_time', models.IntegerField(blank=True, null=True)),
                ('skill_stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.skills')),
            ],
            options={
                'verbose_name': 'Навык и опыт',
                'verbose_name_plural': 'Навыки и опыт',
                'ordering': ['skill_stack'],
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skill_stack',
            field=models.ManyToManyField(null=True, related_name='vacancies', to='recruitment.skillstack', verbose_name='Ключевые навыки'),
        ),
    ]
