# Generated by Django 4.1 on 2023-08-24 08:39

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_event_end_time_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantresume',
            name='interview_status',
            field=models.CharField(choices=[('PS', 'Первичный скрининг'), ('IHR', 'Интервью с HR'), ('IHD', 'Интервью с руководителем'), ('TT', 'Тестовое задание'), ('CTT', 'Выполнил тестовое задание'), ('IT', 'Интервью с командой'), ('O', 'Оффер')], default='PS', max_length=3, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='applicantresume',
            name='relocation',
            field=models.CharField(choices=[('VZ', 'Возможен'), ('NV', 'Невозможен'), ('GL', 'Желателен'), ('NG', 'Нежелателен')], default='NG', max_length=2, verbose_name='Переезд'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(null=True, verbose_name='Срок закрытия вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PO', 'Полная'), ('CH', 'Частичная'), ('PR', 'Проектная'), ('ST', 'Стажировка'), ('VO', 'Волонтерство')], default=['PO'], max_length=14, null=True, verbose_name='Тип занятости'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job_conditions',
            field=models.TextField(help_text='Введите условия работы', null=True, verbose_name='Условия работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job_responsibilities',
            field=models.TextField(help_text='Введите обязанности кандидата', null=True, verbose_name='Обязанности кандидата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='required_experience',
            field=models.CharField(choices=[('1', 'Без опыта'), ('2', '1-3 года'), ('3', '3-5 лет'), ('4', 'Более 5 лет')], max_length=1, null=True, verbose_name='Требуемый опыт работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule_work',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('P', 'Полный день'), ('S', 'Сменный график'), ('G', 'Гибкий график'), ('U', 'Удаленная работа'), ('W', 'Вахтовый метод')], default=['P'], max_length=9, null=True, verbose_name='Расписание работы'),
        ),
    ]
