# Generated by Django 4.1 on 2023-09-27 15:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_skills_remove_vacancy_technology_stack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillstack',
            name='vacancy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skill_stacks', to='recruitment.vacancy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(default=datetime.date(2023, 10, 27), verbose_name='Срок закрытия вакансии'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 9, 27), null=True, verbose_name='Дата увольнения'),
        ),
    ]
