# Generated by Django 4.1 on 2023-08-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_alter_funnelstage_status_alter_substage_status'),
        ('recruitment', '0009_applicantresume_interview_status_and_more'),
    ]

    operations = [
    ]
