# Generated by Django 4.1 on 2023-08-25 04:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_remove_event_user_event_hr_alter_event_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salar',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=2, verbose_name='Зп'),
        ),
    ]
