# Generated by Django 4.1 on 2023-08-25 04:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0013_vacancy_salar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='salary',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salar',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=2, verbose_name='Оплата труда'),
        ),
    ]
