# Generated by Django 4.1 on 2023-08-25 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_remove_vacancy_salary_alter_vacancy_salar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='salar',
            new_name='salary',
        ),
    ]
