# Generated by Django 4.1 on 2023-08-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0015_rename_salar_vacancy_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='status',
            new_name='vacancy_status',
        ),
    ]
