# Generated by Django 4.1 on 2023-08-25 06:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0017_remove_applicantresume_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantresume',
            name='salary_expectations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=2, verbose_name='Желаемая зарплата'),
        ),
    ]
