# Generated by Django 4.1 on 2023-08-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_candidate_note_event_comment_and_more'),
        ('recruitment', '0018_applicantresume_salary_expectations'),
    ]

    operations = [
    ]
