# Generated by Django 4.1 on 2023-07-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Соискатель', 'Applicant'), ('HR', 'Hr')], default='Соискатель', max_length=11, verbose_name='Роль'),
        ),
    ]
