# Generated by Django 4.1 on 2023-09-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='6df9f02d-566d-4696-bb88-6c627cb0c4ec', editable=False, max_length=40),
        ),
    ]
