# Generated by Django 4.1 on 2023-08-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='2a1f0ccd-4e4e-4f46-a5b9-db59c71cc83e', editable=False, max_length=40),
        ),
    ]
