# Generated by Django 4.1 on 2023-09-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='56b0ab61-c410-46aa-b17d-642015f39bb9', editable=False, max_length=40),
        ),
    ]
