# Generated by Django 4.1 on 2023-08-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='1f1808a1-4b51-42fd-9bf4-2d6f8ebf3d1f', editable=False, max_length=40),
        ),
    ]
