# Generated by Django 4.1 on 2023-08-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_confirmation_code_user_email_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='cc3d165b-3db9-4ee7-aeba-52fe31ebc55a', editable=False, max_length=40),
        ),
    ]
