# Generated by Django 4.1 on 2023-09-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='a77ee462-b62c-4de1-9cbd-98067313d0db', editable=False, max_length=40),
        ),
    ]
