# Generated by Django 4.1 on 2023-09-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='6313d1eb-3478-4dfd-924f-4b258cc4e229', editable=False, max_length=40),
        ),
    ]
