# Generated by Django 4.1 on 2023-09-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='f1ce3770-bb53-43ab-97ed-52007ddae061', editable=False, max_length=40),
        ),
    ]
