name: Commit tests

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - develop
      - feature/alter-user-model
      - auth
      - feature/recruitment
  pull_request:
    paths-ignore:
      - '**.md'
    branches: [ develop ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming flake8-broken-line flake8-return
        pip install -r requirements.txt

    - name: Test with flake8 and django tests
      run: |
        python -m flake8
        cd crm_backend/
        python manage.py test
